version: '3.9'
services:
  nuxt:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    tty: true
    working_dir: /app
    command: yarn run dev